spring.application.name=task-management-app
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQLDB_DATABASE}
spring.datasource.username=${MYSQLDB_USER}
spring.datasource.password=${MYSQLDB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.expiration-time=${JWT_EXPIRATION_TIME}
jwt.secret=${JWT_SECRET}

dropbox.access-token=${DROPBOX_ACCESS_TOKEN}
